name: GitHub Actions Pipeline for Node.js App Deployment to AKS

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean workspace
      run: |
        git clean -fdx

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Docker Build and Push
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/nodejs-app:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/nodejs-app:${{ github.sha }}

    - name: Setup Kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy to AKS
      run: ""
